
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>.catch() - Bluebird - W3cubDocs</title>
  
  <meta name="description" content=".catch is a convenience method for handling errors in promise chains. It comes in two variants - A catch-all variant similar to the synchronous &hellip;">
  <meta name="keywords" content="catch, bluebird">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/bluebird/api/catch.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e498cd0ebe8746846fec95b1a53ab3bb0fb7f47f794f0a38f44c98a1f0d03b21d777ae2c583732e44a5a890f6eacb79a5333545db9d5f3616091ba21ca17d916.css">
  <script src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js" type="text/javascript"></script>
  <script src="/json/bluebird.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/bluebird/" class="_nav-link" title="" style="margin-left:0;">Bluebird</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _simple">
				
				
<h1 id="catch">  .catch </h1> <p><code>.catch</code> is a convenience method for handling errors in promise chains. It comes in two variants - A catch-all variant similar to the synchronous <code>catch(e) {</code> block. This variant is compatible with native promises. - A filtered variant (like other non-JS languages typically have) that lets you only handle specific errors. <strong>This variant is usually preferable and is significantly safer</strong>. </p> <h3 id="a-note-on-promise-exception-handling">  A note on promise exception handling. </h3> <p>Promise exception handling mirrors native exception handling in JavaScript. A synchronous function <code>throw</code>ing is similar to a promise rejecting. Here is an example to illustrate it:</p> <pre data-language="javascript">function getItems(param) {
    try { 
        var items = getItemsSync();
        if(!items) throw new InvalidItemsError();  
    } catch(e) { 
        // can address the error here, either from getItemsSync returning a falsey value or throwing itself
        throw e; // need to re-throw the error unless I want it to be considered handled. 
    }
    return process(items);
}
</pre> <p>Similarly, with promises:</p> <pre data-language="javascript">function getItems(param) {
    return getItemsAsync().then(items =&gt; {
        if(!items) throw new InvalidItemsError(); 
        return items;
    }).catch(e =&gt; {
        // can address the error here and recover from it, from getItemsAsync rejects or returns a falsey value
        throw e; // Need to rethrow unless we actually recovered, just like in the synchronous version
    }).then(process);
}
</pre> <h3 id="catch-all">  Catch-all </h3> <pre data-language="javascript">.catch(function(any error) handler) -&gt; Promise
</pre>
<pre data-language="javascript">.caught(function(any error) handler) -&gt; Promise
</pre> <p>This is a catch-all exception handler, shortcut for calling <a href="then"><code>.then(null, handler)</code></a> on this promise. Any exception happening in a <code>.then</code>-chain will propagate to nearest <code>.catch</code> handler.</p> <p><em>For compatibility with earlier ECMAScript versions, an alias <code>.caught</code> is provided for <a href="catch"><code>.catch</code></a>.</em></p> <h3 id="filtered-catch">  Filtered Catch </h3> <pre data-language="javascript">.catch(
    class ErrorClass|function(any error)|Object predicate...,
    function(any error) handler
) -&gt; Promise
</pre>
<pre data-language="javascript">.caught(
    class ErrorClass|function(any error)|Object predicate...,
    function(any error) handler
) -&gt; Promise
</pre> <p>This is an extension to <a href="catch"><code>.catch</code></a> to work more like catch-clauses in languages like Java or C#. Instead of manually checking <code>instanceof</code> or <code>.name === "SomeError"</code>, you may specify a number of error constructors which are eligible for this catch handler. The catch handler that is first met that has eligible constructors specified, is the one that will be called.</p> <p>Example:</p> <pre data-language="javascript">somePromise.then(function() {
    return a.b.c.d();
}).catch(TypeError, function(e) {
    //If it is a TypeError, will end up here because
    //it is a type error to reference property of undefined
}).catch(ReferenceError, function(e) {
    //Will end up here if a was never declared at all
}).catch(function(e) {
    //Generic catch-the rest, error wasn't TypeError nor
    //ReferenceError
});
</pre> <p>You may also add multiple filters for a catch handler:</p> <pre data-language="javascript">somePromise.then(function() {
    return a.b.c.d();
}).catch(TypeError, ReferenceError, function(e) {
    //Will end up here on programmer error
}).catch(NetworkError, TimeoutError, function(e) {
    //Will end up here on expected everyday network errors
}).catch(function(e) {
    //Catch any unexpected errors
});
</pre> <p>For a parameter to be considered a type of error that you want to filter, you need the constructor to have its <code>.prototype</code> property be <code>instanceof Error</code>.</p> <p>Such a constructor can be minimally created like so:</p> <pre data-language="javascript">function MyCustomError() {}
MyCustomError.prototype = Object.create(Error.prototype);
</pre> <p>Using it:</p> <pre data-language="javascript">Promise.resolve().then(function() {
    throw new MyCustomError();
}).catch(MyCustomError, function(e) {
    //will end up here now
});
</pre> <p>However if you want stack traces and cleaner string output, then you should do:</p> <p><em>in Node.js and other V8 environments, with support for <code>Error.captureStackTrace</code></em></p> <pre data-language="javascript">function MyCustomError(message) {
    this.message = message;
    this.name = "MyCustomError";
    Error.captureStackTrace(this, MyCustomError);
}
MyCustomError.prototype = Object.create(Error.prototype);
MyCustomError.prototype.constructor = MyCustomError;
</pre> <p>Using CoffeeScript's <code>class</code> for the same:</p> <pre data-language="javascript">class MyCustomError extends Error
  constructor: (@message) -&gt;
    @name = "MyCustomError"
    Error.captureStackTrace(this, MyCustomError)
</pre> <p>This method also supports predicate-based filters. If you pass a predicate function instead of an error constructor, the predicate will receive the error as an argument. The return result of the predicate will be used determine whether the error handler should be called.</p> <p>Predicates should allow for very fine grained control over caught errors: pattern matching, error-type sets with set operations and many other techniques can be implemented on top of them.</p> <p>Example of using a predicate-based filter:</p> <pre data-language="javascript">var Promise = require("bluebird");
var request = Promise.promisify(require("request"));

function ClientError(e) {
    return e.code &gt;= 400 &amp;&amp; e.code &lt; 500;
}

request("http://www.google.com").then(function(contents) {
    console.log(contents);
}).catch(ClientError, function(e) {
   //A client error like 400 Bad Request happened
});
</pre> <p>Predicate functions that only check properties have a handy shorthand. In place of a predicate function, you can pass an object, and its properties will be checked against the error object for a match:</p> <pre data-language="javascript">fs.readFileAsync(...)
    .then(...)
    .catch({code: 'ENOENT'}, function(e) {
        console.log("file not found: " + e.path);
    });
</pre> <p>The object predicate passed to <code>.catch</code> in the above code (<code>{code: 'ENOENT'}</code>) is shorthand for a predicate function <code>function predicate(e) { return isObject(e) &amp;&amp; e.code == 'ENOENT' }</code>, I.E. loose equality is used.</p> <p><em>For compatibility with earlier ECMAScript version, an alias <code>.caught</code> is provided for <a href="catch"><code>.catch</code></a>.</em> </p> <p>By not returning a rejected value or <code>throw</code>ing from a catch, you "recover from failure" and continue the chain:</p> <pre data-language="javascript">Promise.reject(Error('fail!'))
  .catch(function(e) {
    // fallback with "recover from failure"
    return Promise.resolve('success!'); // promise or value
  })
  .then(function(result) {
    console.log(result); // will print "success!"
  });
</pre> <p>This is exactly like the synchronous code:</p> <pre data-language="javascript">var result;
try {
  throw Error('fail');
} catch(e) {
  result = 'success!';
}
console.log(result);
</pre>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
</noscript>
<div class="_attribution">
  <p class="_attribution-p">
    © 2013–2018 Petka Antonov<br>Licensed under the MIT License.<br>
    <a href="http://bluebirdjs.com/docs/api/catch.html" class="_attribution-link">http://bluebirdjs.com/docs/api/catch.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
