
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Exceptions - Python 2.7 - W3cubDocs</title>
  
  <meta name="description" content="Exceptions should be class objects. The exceptions are defined in the module exceptions. This module never needs to be imported explicitly&#58; the &hellip;">
  <meta name="keywords" content="built-in, exceptions, python, python~2.7">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/python~2.7/library/exceptions.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e498cd0ebe8746846fec95b1a53ab3bb0fb7f47f794f0a38f44c98a1f0d03b21d777ae2c583732e44a5a890f6eacb79a5333545db9d5f3616091ba21ca17d916.css">
  <script src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js" type="text/javascript"></script>
  <script src="/json/python~2.7.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/python~2.7/" class="_nav-link" title="" style="margin-left:0;">Python 2.7</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _python">
				
				
<h1 id="bltin-exceptions"> Built-in Exceptions</h1> <p id="module-exceptions">Exceptions should be class objects. The exceptions are defined in the module <a class="reference internal" href="#module-exceptions" title="exceptions: Standard exception classes."><code>exceptions</code></a>. This module never needs to be imported explicitly: the exceptions are provided in the built-in namespace as well as the <a class="reference internal" href="#module-exceptions" title="exceptions: Standard exception classes."><code>exceptions</code></a> module.</p> <p id="index-0">For class exceptions, in a <a class="reference internal" href="https://docs.python.org/2.7/reference/compound_stmts.html#try"><code>try</code></a> statement with an <a class="reference internal" href="https://docs.python.org/2.7/reference/compound_stmts.html#except"><code>except</code></a> clause that mentions a particular class, that clause also handles any exception classes derived from that class (but not exception classes from which <em>it</em> is derived). Two exception classes that are not related via subclassing are never equivalent, even if they have the same name.</p> <p id="index-1">The built-in exceptions listed below can be generated by the interpreter or built-in functions. Except where mentioned, they have an “associated value” indicating the detailed cause of the error. This may be a string or a tuple containing several items of information (e.g., an error code and a string explaining the code). The associated value is the second argument to the <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#raise"><code>raise</code></a> statement. If the exception class is derived from the standard root class <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>, the associated value is present as the exception instance’s <code>args</code> attribute.</p> <p>User code can raise built-in exceptions. This can be used to test an exception handler or to report an error condition “just like” the situation in which the interpreter raises the same exception; but beware that there is nothing to prevent user code from raising an inappropriate error.</p> <p>The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new exceptions from the <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a> class or one of its subclasses, and not from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>. More information on defining exceptions is available in the Python Tutorial under <a class="reference internal" href="https://docs.python.org/2.7/tutorial/errors.html#tut-userexceptions"><span class="std std-ref">User-defined Exceptions</span></a>.</p> <p>The following exceptions are only used as base classes for other exceptions.</p> <dl class="exception"> <dt id="exceptions.BaseException">
<code>exception BaseException</code> </dt> <dd>
<p>The base class for all built-in exceptions. It is not meant to be directly inherited by user-defined classes (for that, use <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a>). If <a class="reference internal" href="functions#str" title="str"><code>str()</code></a> or <a class="reference internal" href="functions#unicode" title="unicode"><code>unicode()</code></a> is called on an instance of this class, the representation of the argument(s) to the instance are returned, or the empty string when there were no arguments.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.5.</span></p> </div> <dl class="attribute"> <dt id="exceptions.BaseException.args">
<code>args</code> </dt> <dd>
<p>The tuple of arguments given to the exception constructor. Some built-in exceptions (like <a class="reference internal" href="#exceptions.IOError" title="exceptions.IOError"><code>IOError</code></a>) expect a certain number of arguments and assign a special meaning to the elements of this tuple, while others are usually called only with a single string giving an error message.</p> </dd>
</dl> </dd>
</dl> <dl class="exception"> <dt id="exceptions.Exception">
<code>exception Exception</code> </dt> <dd>
<p>All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.StandardError">
<code>exception StandardError</code> </dt> <dd>
<p>The base class for all built-in exceptions except <a class="reference internal" href="#exceptions.StopIteration" title="exceptions.StopIteration"><code>StopIteration</code></a>, <a class="reference internal" href="#exceptions.GeneratorExit" title="exceptions.GeneratorExit"><code>GeneratorExit</code></a>, <a class="reference internal" href="#exceptions.KeyboardInterrupt" title="exceptions.KeyboardInterrupt"><code>KeyboardInterrupt</code></a> and <a class="reference internal" href="#exceptions.SystemExit" title="exceptions.SystemExit"><code>SystemExit</code></a>. <a class="reference internal" href="#exceptions.StandardError" title="exceptions.StandardError"><code>StandardError</code></a> itself is derived from <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ArithmeticError">
<code>exception ArithmeticError</code> </dt> <dd>
<p>The base class for those built-in exceptions that are raised for various arithmetic errors: <a class="reference internal" href="#exceptions.OverflowError" title="exceptions.OverflowError"><code>OverflowError</code></a>, <a class="reference internal" href="#exceptions.ZeroDivisionError" title="exceptions.ZeroDivisionError"><code>ZeroDivisionError</code></a>, <a class="reference internal" href="#exceptions.FloatingPointError" title="exceptions.FloatingPointError"><code>FloatingPointError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.BufferError">
<code>exception BufferError</code> </dt> <dd>
<p>Raised when a <a class="reference internal" href="https://docs.python.org/2.7/c-api/buffer.html#bufferobjects"><span class="std std-ref">buffer</span></a> related operation cannot be performed.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.LookupError">
<code>exception LookupError</code> </dt> <dd>
<p>The base class for the exceptions that are raised when a key or index used on a mapping or sequence is invalid: <a class="reference internal" href="#exceptions.IndexError" title="exceptions.IndexError"><code>IndexError</code></a>, <a class="reference internal" href="#exceptions.KeyError" title="exceptions.KeyError"><code>KeyError</code></a>. This can be raised directly by <a class="reference internal" href="codecs#codecs.lookup" title="codecs.lookup"><code>codecs.lookup()</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.EnvironmentError">
<code>exception EnvironmentError</code> </dt> <dd>
<p>The base class for exceptions that can occur outside the Python system: <a class="reference internal" href="#exceptions.IOError" title="exceptions.IOError"><code>IOError</code></a>, <a class="reference internal" href="#exceptions.OSError" title="exceptions.OSError"><code>OSError</code></a>. When exceptions of this type are created with a 2-tuple, the first item is available on the instance’s <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a> attribute (it is assumed to be an error number), and the second item is available on the <code>strerror</code> attribute (it is usually the associated error message). The tuple itself is also available on the <code>args</code> attribute.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 1.5.2.</span></p> </div> <p>When an <a class="reference internal" href="#exceptions.EnvironmentError" title="exceptions.EnvironmentError"><code>EnvironmentError</code></a> exception is instantiated with a 3-tuple, the first two items are available as above, while the third item is available on the <code>filename</code> attribute. However, for backwards compatibility, the <code>args</code> attribute contains only a 2-tuple of the first two constructor arguments.</p> <p>The <code>filename</code> attribute is <code>None</code> when this exception is created with other than 3 arguments. The <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a> and <code>strerror</code> attributes are also <code>None</code> when the instance was created with other than 2 or 3 arguments. In this last case, <code>args</code> contains the verbatim constructor arguments as a tuple.</p> </dd>
</dl> <p>The following exceptions are the exceptions that are actually raised.</p> <dl class="exception"> <dt id="exceptions.AssertionError">
<code>exception AssertionError</code> </dt> <dd>
<p id="index-2">Raised when an <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#assert"><code>assert</code></a> statement fails.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.AttributeError">
<code>exception AttributeError</code> </dt> <dd>
<p>Raised when an attribute reference (see <a class="reference internal" href="https://docs.python.org/2.7/reference/expressions.html#attribute-references"><span class="std std-ref">Attribute references</span></a>) or assignment fails. (When an object does not support attribute references or attribute assignments at all, <a class="reference internal" href="#exceptions.TypeError" title="exceptions.TypeError"><code>TypeError</code></a> is raised.)</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.EOFError">
<code>exception EOFError</code> </dt> <dd>
<p>Raised when one of the built-in functions (<a class="reference internal" href="functions#input" title="input"><code>input()</code></a> or <a class="reference internal" href="functions#raw_input" title="raw_input"><code>raw_input()</code></a>) hits an end-of-file condition (EOF) without reading any data. (N.B.: the <a class="reference internal" href="stdtypes#file.read" title="file.read"><code>file.read()</code></a> and <a class="reference internal" href="stdtypes#file.readline" title="file.readline"><code>file.readline()</code></a> methods return an empty string when they hit EOF.)</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.FloatingPointError">
<code>exception FloatingPointError</code> </dt> <dd>
<p>Raised when a floating point operation fails. This exception is always defined, but can only be raised when Python is configured with the <code>--with-fpectl</code> option, or the <code>WANT_SIGFPE_HANDLER</code> symbol is defined in the <code>pyconfig.h</code> file.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.GeneratorExit">
<code>exception GeneratorExit</code> </dt> <dd>
<p>Raised when a <a class="reference internal" href="https://docs.python.org/2.7/glossary.html#term-generator"><span class="xref std std-term">generator</span></a>’s <code>close()</code> method is called. It directly inherits from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a> instead of <a class="reference internal" href="#exceptions.StandardError" title="exceptions.StandardError"><code>StandardError</code></a> since it is technically not an error.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.5.</span></p> </div> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.6: </span>Changed to inherit from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.IOError">
<code>exception IOError</code> </dt> <dd>
<p>Raised when an I/O operation (such as a <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#print"><code>print</code></a> statement, the built-in <a class="reference internal" href="functions#open" title="open"><code>open()</code></a> function or a method of a file object) fails for an I/O-related reason, e.g., “file not found” or “disk full”.</p> <p>This class is derived from <a class="reference internal" href="#exceptions.EnvironmentError" title="exceptions.EnvironmentError"><code>EnvironmentError</code></a>. See the discussion above for more information on exception instance attributes.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.6: </span>Changed <a class="reference internal" href="socket#socket.error" title="socket.error"><code>socket.error</code></a> to use this as a base class.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ImportError">
<code>exception ImportError</code> </dt> <dd>
<p>Raised when an <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#import"><code>import</code></a> statement fails to find the module definition or when a <code>from ... import</code> fails to find a name that is to be imported.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.IndexError">
<code>exception IndexError</code> </dt> <dd>
<p>Raised when a sequence subscript is out of range. (Slice indices are silently truncated to fall in the allowed range; if an index is not a plain integer, <a class="reference internal" href="#exceptions.TypeError" title="exceptions.TypeError"><code>TypeError</code></a> is raised.)</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.KeyError">
<code>exception KeyError</code> </dt> <dd>
<p>Raised when a mapping (dictionary) key is not found in the set of existing keys.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.KeyboardInterrupt">
<code>exception KeyboardInterrupt</code> </dt> <dd>
<p>Raised when the user hits the interrupt key (normally <kbd class="kbd docutils literal notranslate">Control-C</kbd> or <kbd class="kbd docutils literal notranslate">Delete</kbd>). During execution, a check for interrupts is made regularly. Interrupts typed when a built-in function <a class="reference internal" href="functions#input" title="input"><code>input()</code></a> or <a class="reference internal" href="functions#raw_input" title="raw_input"><code>raw_input()</code></a> is waiting for input also raise this exception. The exception inherits from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a> so as to not be accidentally caught by code that catches <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a> and thus prevent the interpreter from exiting.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.MemoryError">
<code>exception MemoryError</code> </dt> <dd>
<p>Raised when an operation runs out of memory but the situation may still be rescued (by deleting some objects). The associated value is a string indicating what kind of (internal) operation ran out of memory. Note that because of the underlying memory management architecture (C’s <code>malloc()</code> function), the interpreter may not always be able to completely recover from this situation; it nevertheless raises an exception so that a stack traceback can be printed, in case a run-away program was the cause.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.NameError">
<code>exception NameError</code> </dt> <dd>
<p>Raised when a local or global name is not found. This applies only to unqualified names. The associated value is an error message that includes the name that could not be found.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.NotImplementedError">
<code>exception NotImplementedError</code> </dt> <dd>
<p>This exception is derived from <a class="reference internal" href="#exceptions.RuntimeError" title="exceptions.RuntimeError"><code>RuntimeError</code></a>. In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 1.5.2.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.OSError">
<code>exception OSError</code> </dt> <dd>
<p id="index-3">This exception is derived from <a class="reference internal" href="#exceptions.EnvironmentError" title="exceptions.EnvironmentError"><code>EnvironmentError</code></a>. It is raised when a function returns a system-related error (not for illegal argument types or other incidental errors). The <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a> attribute is a numeric error code from <code>errno</code>, and the <code>strerror</code> attribute is the corresponding string, as would be printed by the C function <code>perror()</code>. See the module <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a>, which contains names for the error codes defined by the underlying operating system.</p> <p>For exceptions that involve a file system path (such as <code>chdir()</code> or <code>unlink()</code>), the exception instance will contain a third attribute, <code>filename</code>, which is the file name passed to the function.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 1.5.2.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.OverflowError">
<code>exception OverflowError</code> </dt> <dd>
<p>Raised when the result of an arithmetic operation is too large to be represented. This cannot occur for long integers (which would rather raise <a class="reference internal" href="#exceptions.MemoryError" title="exceptions.MemoryError"><code>MemoryError</code></a> than give up) and for most operations with plain integers, which return a long integer instead. Because of the lack of standardization of floating point exception handling in C, most floating point operations also aren’t checked.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ReferenceError">
<code>exception ReferenceError</code> </dt> <dd>
<p>This exception is raised when a weak reference proxy, created by the <a class="reference internal" href="weakref#weakref.proxy" title="weakref.proxy"><code>weakref.proxy()</code></a> function, is used to access an attribute of the referent after it has been garbage collected. For more information on weak references, see the <a class="reference internal" href="weakref#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code>weakref</code></a> module.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.2: </span>Previously known as the <a class="reference internal" href="weakref#weakref.ReferenceError" title="weakref.ReferenceError"><code>weakref.ReferenceError</code></a> exception.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.RuntimeError">
<code>exception RuntimeError</code> </dt> <dd>
<p>Raised when an error is detected that doesn’t fall in any of the other categories. The associated value is a string indicating what precisely went wrong.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.StopIteration">
<code>exception StopIteration</code> </dt> <dd>
<p>Raised by an <a class="reference internal" href="https://docs.python.org/2.7/glossary.html#term-iterator"><span class="xref std std-term">iterator</span></a>’s <a class="reference internal" href="stdtypes#iterator.next" title="iterator.next"><code>next()</code></a> method to signal that there are no further values. This is derived from <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a> rather than <a class="reference internal" href="#exceptions.StandardError" title="exceptions.StandardError"><code>StandardError</code></a>, since this is not considered an error in its normal application.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.2.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.SyntaxError">
<code>exception SyntaxError</code> </dt> <dd>
<p>Raised when the parser encounters a syntax error. This may occur in an <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#import"><code>import</code></a> statement, in an <a class="reference internal" href="https://docs.python.org/2.7/reference/simple_stmts.html#exec"><code>exec</code></a> statement, in a call to the built-in function <a class="reference internal" href="functions#eval" title="eval"><code>eval()</code></a> or <a class="reference internal" href="functions#input" title="input"><code>input()</code></a>, or when reading the initial script or standard input (also interactively).</p> <p>Instances of this class have attributes <code>filename</code>, <code>lineno</code>, <code>offset</code> and <code>text</code> for easier access to the details. <a class="reference internal" href="functions#str" title="str"><code>str()</code></a> of the exception instance returns only the message.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.IndentationError">
<code>exception IndentationError</code> </dt> <dd>
<p>Base class for syntax errors related to incorrect indentation. This is a subclass of <a class="reference internal" href="#exceptions.SyntaxError" title="exceptions.SyntaxError"><code>SyntaxError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.TabError">
<code>exception TabError</code> </dt> <dd>
<p>Raised when indentation contains an inconsistent use of tabs and spaces. This is a subclass of <a class="reference internal" href="#exceptions.IndentationError" title="exceptions.IndentationError"><code>IndentationError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.SystemError">
<code>exception SystemError</code> </dt> <dd>
<p>Raised when the interpreter finds an internal error, but the situation does not look so serious to cause it to abandon all hope. The associated value is a string indicating what went wrong (in low-level terms).</p> <p>You should report this to the author or maintainer of your Python interpreter. Be sure to report the version of the Python interpreter (<code>sys.version</code>; it is also printed at the start of an interactive Python session), the exact error message (the exception’s associated value) and if possible the source of the program that triggered the error.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.SystemExit">
<code>exception SystemExit</code> </dt> <dd>
<p>This exception is raised by the <a class="reference internal" href="sys#sys.exit" title="sys.exit"><code>sys.exit()</code></a> function. When it is not handled, the Python interpreter exits; no stack traceback is printed. If the associated value is a plain integer, it specifies the system exit status (passed to C’s <code>exit()</code> function); if it is <code>None</code>, the exit status is zero; if it has another type (such as a string), the object’s value is printed and the exit status is one.</p> <p>Instances have an attribute <code>code</code> which is set to the proposed exit status or error message (defaulting to <code>None</code>). Also, this exception derives directly from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a> and not <a class="reference internal" href="#exceptions.StandardError" title="exceptions.StandardError"><code>StandardError</code></a>, since it is not technically an error.</p> <p>A call to <a class="reference internal" href="sys#sys.exit" title="sys.exit"><code>sys.exit()</code></a> is translated into an exception so that clean-up handlers (<a class="reference internal" href="https://docs.python.org/2.7/reference/compound_stmts.html#finally"><code>finally</code></a> clauses of <a class="reference internal" href="https://docs.python.org/2.7/reference/compound_stmts.html#try"><code>try</code></a> statements) can be executed, and so that a debugger can execute a script without running the risk of losing control. The <a class="reference internal" href="os#os._exit" title="os._exit"><code>os._exit()</code></a> function can be used if it is absolutely positively necessary to exit immediately (for example, in the child process after a call to <a class="reference internal" href="os#os.fork" title="os.fork"><code>os.fork()</code></a>).</p> <p>The exception inherits from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a> instead of <a class="reference internal" href="#exceptions.StandardError" title="exceptions.StandardError"><code>StandardError</code></a> or <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a> so that it is not accidentally caught by code that catches <a class="reference internal" href="#exceptions.Exception" title="exceptions.Exception"><code>Exception</code></a>. This allows the exception to properly propagate up and cause the interpreter to exit.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="#exceptions.BaseException" title="exceptions.BaseException"><code>BaseException</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.TypeError">
<code>exception TypeError</code> </dt> <dd>
<p>Raised when an operation or function is applied to an object of inappropriate type. The associated value is a string giving details about the type mismatch.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnboundLocalError">
<code>exception UnboundLocalError</code> </dt> <dd>
<p>Raised when a reference is made to a local variable in a function or method, but no value has been bound to that variable. This is a subclass of <a class="reference internal" href="#exceptions.NameError" title="exceptions.NameError"><code>NameError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.0.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnicodeError">
<code>exception UnicodeError</code> </dt> <dd>
<p>Raised when a Unicode-related encoding or decoding error occurs. It is a subclass of <a class="reference internal" href="#exceptions.ValueError" title="exceptions.ValueError"><code>ValueError</code></a>.</p> <p><a class="reference internal" href="#exceptions.UnicodeError" title="exceptions.UnicodeError"><code>UnicodeError</code></a> has attributes that describe the encoding or decoding error. For example, <code>err.object[err.start:err.end]</code> gives the particular invalid input that the codec failed on.</p> <dl class="attribute"> <dt id="exceptions.UnicodeError.encoding">
<code>encoding</code> </dt> <dd>
<p>The name of the encoding that raised the error.</p> </dd>
</dl> <dl class="attribute"> <dt id="exceptions.UnicodeError.reason">
<code>reason</code> </dt> <dd>
<p>A string describing the specific codec error.</p> </dd>
</dl> <dl class="attribute"> <dt id="exceptions.UnicodeError.object">
<code>object</code> </dt> <dd>
<p>The object the codec was attempting to encode or decode.</p> </dd>
</dl> <dl class="attribute"> <dt id="exceptions.UnicodeError.start">
<code>start</code> </dt> <dd>
<p>The first index of invalid data in <a class="reference internal" href="functions#object" title="object"><code>object</code></a>.</p> </dd>
</dl> <dl class="attribute"> <dt id="exceptions.UnicodeError.end">
<code>end</code> </dt> <dd>
<p>The index after the last invalid data in <a class="reference internal" href="functions#object" title="object"><code>object</code></a>.</p> </dd>
</dl> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.0.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnicodeEncodeError">
<code>exception UnicodeEncodeError</code> </dt> <dd>
<p>Raised when a Unicode-related error occurs during encoding. It is a subclass of <a class="reference internal" href="#exceptions.UnicodeError" title="exceptions.UnicodeError"><code>UnicodeError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.3.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnicodeDecodeError">
<code>exception UnicodeDecodeError</code> </dt> <dd>
<p>Raised when a Unicode-related error occurs during decoding. It is a subclass of <a class="reference internal" href="#exceptions.UnicodeError" title="exceptions.UnicodeError"><code>UnicodeError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.3.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnicodeTranslateError">
<code>exception UnicodeTranslateError</code> </dt> <dd>
<p>Raised when a Unicode-related error occurs during translating. It is a subclass of <a class="reference internal" href="#exceptions.UnicodeError" title="exceptions.UnicodeError"><code>UnicodeError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.3.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ValueError">
<code>exception ValueError</code> </dt> <dd>
<p>Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as <a class="reference internal" href="#exceptions.IndexError" title="exceptions.IndexError"><code>IndexError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.VMSError">
<code>exception VMSError</code> </dt> <dd>
<p>Only available on VMS. Raised when a VMS-specific error occurs.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.WindowsError">
<code>exception WindowsError</code> </dt> <dd>
<p>Raised when a Windows-specific error occurs or when the error number does not correspond to an <code>errno</code> value. The <code>winerror</code> and <code>strerror</code> values are created from the return values of the <code>GetLastError()</code> and <code>FormatMessage()</code> functions from the Windows Platform API. The <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a> value maps the <code>winerror</code> value to corresponding <code>errno.h</code> values. This is a subclass of <a class="reference internal" href="#exceptions.OSError" title="exceptions.OSError"><code>OSError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.0.</span></p> </div> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 2.5: </span>Previous versions put the <code>GetLastError()</code> codes into <a class="reference internal" href="errno#module-errno" title="errno: Standard errno system symbols."><code>errno</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ZeroDivisionError">
<code>exception ZeroDivisionError</code> </dt> <dd>
<p>Raised when the second argument of a division or modulo operation is zero. The associated value is a string indicating the type of the operands and the operation.</p> </dd>
</dl> <p>The following exceptions are used as warning categories; see the <a class="reference internal" href="warnings#module-warnings" title="warnings: Issue warning messages and control their disposition."><code>warnings</code></a> module for more information.</p> <dl class="exception"> <dt id="exceptions.Warning">
<code>exception Warning</code> </dt> <dd>
<p>Base class for warning categories.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UserWarning">
<code>exception UserWarning</code> </dt> <dd>
<p>Base class for warnings generated by user code.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.DeprecationWarning">
<code>exception DeprecationWarning</code> </dt> <dd>
<p>Base class for warnings about deprecated features.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.PendingDeprecationWarning">
<code>exception PendingDeprecationWarning</code> </dt> <dd>
<p>Base class for warnings about features which will be deprecated in the future.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.SyntaxWarning">
<code>exception SyntaxWarning</code> </dt> <dd>
<p>Base class for warnings about dubious syntax.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.RuntimeWarning">
<code>exception RuntimeWarning</code> </dt> <dd>
<p>Base class for warnings about dubious runtime behavior.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.FutureWarning">
<code>exception FutureWarning</code> </dt> <dd>
<p>Base class for warnings about constructs that will change semantically in the future.</p> </dd>
</dl> <dl class="exception"> <dt id="exceptions.ImportWarning">
<code>exception ImportWarning</code> </dt> <dd>
<p>Base class for warnings about probable mistakes in module imports.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.5.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.UnicodeWarning">
<code>exception UnicodeWarning</code> </dt> <dd>
<p>Base class for warnings related to Unicode.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.5.</span></p> </div> </dd>
</dl> <dl class="exception"> <dt id="exceptions.BytesWarning">
<code>exception BytesWarning</code> </dt> <dd>
<p>Base class for warnings related to bytes and bytearray.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 2.6.</span></p> </div> </dd>
</dl>  <h2 id="exception-hierarchy">1. Exception hierarchy</h2> <p>The class hierarchy for built-in exceptions is:</p> <pre data-language="python">BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StandardError
      |    +-- BufferError
      |    +-- ArithmeticError
      |    |    +-- FloatingPointError
      |    |    +-- OverflowError
      |    |    +-- ZeroDivisionError
      |    +-- AssertionError
      |    +-- AttributeError
      |    +-- EnvironmentError
      |    |    +-- IOError
      |    |    +-- OSError
      |    |         +-- WindowsError (Windows)
      |    |         +-- VMSError (VMS)
      |    +-- EOFError
      |    +-- ImportError
      |    +-- LookupError
      |    |    +-- IndexError
      |    |    +-- KeyError
      |    +-- MemoryError
      |    +-- NameError
      |    |    +-- UnboundLocalError
      |    +-- ReferenceError
      |    +-- RuntimeError
      |    |    +-- NotImplementedError
      |    +-- SyntaxError
      |    |    +-- IndentationError
      |    |         +-- TabError
      |    +-- SystemError
      |    +-- TypeError
      |    +-- ValueError
      |         +-- UnicodeError
      |              +-- UnicodeDecodeError
      |              +-- UnicodeEncodeError
      |              +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
	   +-- ImportWarning
	   +-- UnicodeWarning
	   +-- BytesWarning
</pre>
<div class="_attribution">
  <p class="_attribution-p">
    © 2001–2020 Python Software Foundation<br>Licensed under the PSF License.<br>
    <a href="https://docs.python.org/2.7/library/exceptions.html" class="_attribution-link">https://docs.python.org/2.7/library/exceptions.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
