
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>HTTP Exceptions - Werkzeug 1.0 - W3cubDocs</title>
  
  <meta name="description" content=" This module implements a number of Python exceptions you can raise from within your views to trigger a standard non-200 response. ">
  <meta name="keywords" content="http, exceptions, werkzeug, werkzeug~1.0">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/werkzeug~1.0/exceptions/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e498cd0ebe8746846fec95b1a53ab3bb0fb7f47f794f0a38f44c98a1f0d03b21d777ae2c583732e44a5a890f6eacb79a5333545db9d5f3616091ba21ca17d916.css">
  <script src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js" type="text/javascript"></script>
  <script src="/json/werkzeug~1.0.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/werkzeug~1.0/" class="_nav-link" title="" style="margin-left:0;">Werkzeug 1.0</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _sphinx">
				
				
<h1 id="http-exceptions">HTTP Exceptions</h1>  <h2 id="werkzeug-exceptions">werkzeug.exceptions</h2> <p>This module implements a number of Python exceptions you can raise from within your views to trigger a standard non-200 response.</p>  <h3 id="usage-example">Usage Example</h3> <pre data-language="python">from werkzeug.wrappers import BaseRequest
from werkzeug.wsgi import responder
from werkzeug.exceptions import HTTPException, NotFound

def view(request):
    raise NotFound()

@responder
def application(environ, start_response):
    request = BaseRequest(environ)
    try:
        return view(request)
    except HTTPException as e:
        return e
</pre> <p>As you can see from this example those exceptions are callable WSGI applications. Because of Python 2.4 compatibility those do not extend from the response objects but only from the python exception class.</p> <p>As a matter of fact they are not Werkzeug response objects. However you can get a response object by calling <code>get_response()</code> on a HTTP exception.</p> <p>Keep in mind that you have to pass an environment to <code>get_response()</code> because some errors fetch additional information from the WSGI environment.</p> <p>If you want to hook in a different exception page to say, a 404 status code, you can add a second except for a specific subclass of an error:</p> <pre data-language="python">@responder
def application(environ, start_response):
    request = BaseRequest(environ)
    try:
        return view(request)
    except NotFound, e:
        return not_found(request)
    except HTTPException, e:
        return e
</pre>    <h2 id="error-classes">Error Classes</h2> <p>The following error classes exist in Werkzeug:</p> <dl class="exception"> <dt id="werkzeug.exceptions.BadRequest">
<code>exception werkzeug.exceptions.BadRequest(description=None, response=None)</code> </dt> <dd>
<p><em>400</em> <code>Bad Request</code></p> <p>Raise if the browser sends something to the application the application or server cannot handle.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.Unauthorized">
<code>exception werkzeug.exceptions.Unauthorized(description=None, response=None, www_authenticate=None)</code> </dt> <dd>
<p><em>401</em> <code>Unauthorized</code></p> <p>Raise if the user is not authorized to access a resource.</p> <p>The <code>www_authenticate</code> argument should be used to set the <code>WWW-Authenticate</code> header. This is used for HTTP basic auth and other schemes. Use <a class="reference internal" href="../datastructures/index#werkzeug.datastructures.WWWAuthenticate" title="werkzeug.datastructures.WWWAuthenticate"><code>WWWAuthenticate</code></a> to create correctly formatted values. Strictly speaking a 401 response is invalid if it doesn’t provide at least one value for this header, although real clients typically don’t care.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr>
<th class="field-name">Parameters:</th>
<td class="field-body">
<ul class="first last simple"> <li>
<strong>description</strong> – Override the default message used for the body of the response.</li> <li>
<strong>www-authenticate</strong> – A single value, or list of values, for the WWW-Authenticate header.</li> </ul> </td> </tr>  </table> <details class="changelog"> <summary>Changelog</summary><div class="versionchanged"> <p><span class="versionmodified">Changed in version 0.15.3: </span>If the <code>www_authenticate</code> argument is not set, the <code>WWW-Authenticate</code> header is not set.</p> </div> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 0.15.3: </span>The <code>response</code> argument was restored.</p> </div> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 0.15.1: </span><code>description</code> was moved back as the first argument, restoring its previous position.</p> </div> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 0.15.0: </span><code>www_authenticate</code> was added as the first argument, ahead of <code>description</code>.</p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.Forbidden">
<code>exception werkzeug.exceptions.Forbidden(description=None, response=None)</code> </dt> <dd>
<p><em>403</em> <code>Forbidden</code></p> <p>Raise if the user doesn’t have the permission for the requested resource but was authenticated.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.NotFound">
<code>exception werkzeug.exceptions.NotFound(description=None, response=None)</code> </dt> <dd>
<p><em>404</em> <code>Not Found</code></p> <p>Raise if a resource does not exist and never existed.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.MethodNotAllowed">
<code>exception werkzeug.exceptions.MethodNotAllowed(valid_methods=None, description=None)</code> </dt> <dd>
<p><em>405</em> <code>Method Not Allowed</code></p> <p>Raise if the server used a method the resource does not handle. For example <code>POST</code> if the resource is view only. Especially useful for REST.</p> <p>The first argument for this exception should be a list of allowed methods. Strictly speaking the response would be invalid if you don’t provide valid methods in the header which you can do with that list.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.NotAcceptable">
<code>exception werkzeug.exceptions.NotAcceptable(description=None, response=None)</code> </dt> <dd>
<p><em>406</em> <code>Not Acceptable</code></p> <p>Raise if the server can’t return any content conforming to the <code>Accept</code> headers of the client.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.RequestTimeout">
<code>exception werkzeug.exceptions.RequestTimeout(description=None, response=None)</code> </dt> <dd>
<p><em>408</em> <code>Request Timeout</code></p> <p>Raise to signalize a timeout.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.Conflict">
<code>exception werkzeug.exceptions.Conflict(description=None, response=None)</code> </dt> <dd>
<p><em>409</em> <code>Conflict</code></p> <p>Raise to signal that a request cannot be completed because it conflicts with the current state on the server.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.7.</span></p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.Gone">
<code>exception werkzeug.exceptions.Gone(description=None, response=None)</code> </dt> <dd>
<p><em>410</em> <code>Gone</code></p> <p>Raise if a resource existed previously and went away without new location.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.LengthRequired">
<code>exception werkzeug.exceptions.LengthRequired(description=None, response=None)</code> </dt> <dd>
<p><em>411</em> <code>Length Required</code></p> <p>Raise if the browser submitted data but no <code>Content-Length</code> header which is required for the kind of processing the server does.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.PreconditionFailed">
<code>exception werkzeug.exceptions.PreconditionFailed(description=None, response=None)</code> </dt> <dd>
<p><em>412</em> <code>Precondition Failed</code></p> <p>Status code used in combination with <code>If-Match</code>, <code>If-None-Match</code>, or <code>If-Unmodified-Since</code>.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.RequestEntityTooLarge">
<code>exception werkzeug.exceptions.RequestEntityTooLarge(description=None, response=None)</code> </dt> <dd>
<p><em>413</em> <code>Request Entity Too Large</code></p> <p>The status code one should return if the data submitted exceeded a given limit.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.RequestURITooLarge">
<code>exception werkzeug.exceptions.RequestURITooLarge(description=None, response=None)</code> </dt> <dd>
<p><em>414</em> <code>Request URI Too Large</code></p> <p>Like <em>413</em> but for too long URLs.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.UnsupportedMediaType">
<code>exception werkzeug.exceptions.UnsupportedMediaType(description=None, response=None)</code> </dt> <dd>
<p><em>415</em> <code>Unsupported Media Type</code></p> <p>The status code returned if the server is unable to handle the media type the client transmitted.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.RequestedRangeNotSatisfiable">
<code>exception werkzeug.exceptions.RequestedRangeNotSatisfiable(length=None, units='bytes', description=None)</code> </dt> <dd>
<p><em>416</em> <code>Requested Range Not Satisfiable</code></p> <p>The client asked for an invalid part of the file.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.7.</span></p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.ExpectationFailed">
<code>exception werkzeug.exceptions.ExpectationFailed(description=None, response=None)</code> </dt> <dd>
<p><em>417</em> <code>Expectation Failed</code></p> <p>The server cannot meet the requirements of the Expect request-header.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.7.</span></p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.ImATeapot">
<code>exception werkzeug.exceptions.ImATeapot(description=None, response=None)</code> </dt> <dd>
<p><em>418</em> <code>I’m a teapot</code></p> <p>The server should return this if it is a teapot and someone attempted to brew coffee with it.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.7.</span></p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.UnprocessableEntity">
<code>exception werkzeug.exceptions.UnprocessableEntity(description=None, response=None)</code> </dt> <dd>
<p><em>422</em> <code>Unprocessable Entity</code></p> <p>Used if the request is well formed, but the instructions are otherwise incorrect.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.Locked">
<code>exception werkzeug.exceptions.Locked(description=None, response=None)</code> </dt> <dd>
<p><em>423</em> <code>Locked</code></p> <p>Used if the resource that is being accessed is locked.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.FailedDependency">
<code>exception werkzeug.exceptions.FailedDependency(description=None, response=None)</code> </dt> <dd>
<p><em>424</em> <code>Failed Dependency</code></p> <p>Used if the method could not be performed on the resource because the requested action depended on another action and that action failed.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.PreconditionRequired">
<code>exception werkzeug.exceptions.PreconditionRequired(description=None, response=None)</code> </dt> <dd>
<p><em>428</em> <code>Precondition Required</code></p> <p>The server requires this request to be conditional, typically to prevent the lost update problem, which is a race condition between two or more clients attempting to update a resource through PUT or DELETE. By requiring each client to include a conditional header (“If-Match” or “If-Unmodified- Since”) with the proper value retained from a recent GET request, the server ensures that each client has at least seen the previous revision of the resource.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.TooManyRequests">
<code>exception werkzeug.exceptions.TooManyRequests(description=None, response=None, retry_after=None)</code> </dt> <dd>
<p><em>429</em> <code>Too Many Requests</code></p> <p>The server is limiting the rate at which this user receives responses, and this request exceeds that rate. (The server may use any convenient method to identify users and their request rates). The server may include a “Retry-After” header to indicate how long the user should wait before retrying.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr>
<th class="field-name">Parameters:</th>
<td class="field-body">
<strong>retry_after</strong> – If given, set the <code>Retry-After</code> header to this value. May be an <a class="reference external" href="https://docs.python.org/3/library/functions.html#int" title="(in Python v3.8)"><code>int</code></a> number of seconds or a <a class="reference external" href="https://docs.python.org/3/library/datetime.html#datetime.datetime" title="(in Python v3.8)"><code>datetime</code></a>.</td> </tr>  </table> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 1.0: </span>Added <code>retry_after</code> parameter.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.RequestHeaderFieldsTooLarge">
<code>exception werkzeug.exceptions.RequestHeaderFieldsTooLarge(description=None, response=None)</code> </dt> <dd>
<p><em>431</em> <code>Request Header Fields Too Large</code></p> <p>The server refuses to process the request because the header fields are too large. One or more individual fields may be too large, or the set of all headers is too large.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.UnavailableForLegalReasons">
<code>exception werkzeug.exceptions.UnavailableForLegalReasons(description=None, response=None)</code> </dt> <dd>
<p><em>451</em> <code>Unavailable For Legal Reasons</code></p> <p>This status code indicates that the server is denying access to the resource as a consequence of a legal demand.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.InternalServerError">
<code>exception werkzeug.exceptions.InternalServerError(description=None, response=None, original_exception=None)</code> </dt> <dd>
<p><em>500</em> <code>Internal Server Error</code></p> <p>Raise if an internal server error occurred. This is a good fallback if an unknown error occurred in the dispatcher.</p> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 1.0.0: </span>Added the <a class="reference internal" href="#werkzeug.exceptions.InternalServerError.original_exception" title="werkzeug.exceptions.InternalServerError.original_exception"><code>original_exception</code></a> attribute.</p> </div> <dl class="attribute"> <dt id="werkzeug.exceptions.InternalServerError.original_exception">
<code>original_exception = None</code> </dt> <dd>
<p>The original exception that caused this 500 error. Can be used by frameworks to provide context when handling unexpected errors.</p> </dd>
</dl> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.NotImplemented">
<code>exception werkzeug.exceptions.NotImplemented(description=None, response=None)</code> </dt> <dd>
<p><em>501</em> <code>Not Implemented</code></p> <p>Raise if the application does not support the action requested by the browser.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.BadGateway">
<code>exception werkzeug.exceptions.BadGateway(description=None, response=None)</code> </dt> <dd>
<p><em>502</em> <code>Bad Gateway</code></p> <p>If you do proxying in your application you should return this status code if you received an invalid response from the upstream server it accessed in attempting to fulfill the request.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.ServiceUnavailable">
<code>exception werkzeug.exceptions.ServiceUnavailable(description=None, response=None, retry_after=None)</code> </dt> <dd>
<p><em>503</em> <code>Service Unavailable</code></p> <p>Status code you should return if a service is temporarily unavailable.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr>
<th class="field-name">Parameters:</th>
<td class="field-body">
<strong>retry_after</strong> – If given, set the <code>Retry-After</code> header to this value. May be an <a class="reference external" href="https://docs.python.org/3/library/functions.html#int" title="(in Python v3.8)"><code>int</code></a> number of seconds or a <a class="reference external" href="https://docs.python.org/3/library/datetime.html#datetime.datetime" title="(in Python v3.8)"><code>datetime</code></a>.</td> </tr>  </table> <div class="versionchanged"> <p><span class="versionmodified">Changed in version 1.0: </span>Added <code>retry_after</code> parameter.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.GatewayTimeout">
<code>exception werkzeug.exceptions.GatewayTimeout(description=None, response=None)</code> </dt> <dd>
<p><em>504</em> <code>Gateway Timeout</code></p> <p>Status code you should return if a connection to an upstream server times out.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.HTTPVersionNotSupported">
<code>exception werkzeug.exceptions.HTTPVersionNotSupported(description=None, response=None)</code> </dt> <dd>
<p><em>505</em> <code>HTTP Version Not Supported</code></p> <p>The server does not support the HTTP protocol version used in the request.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.HTTPUnicodeError">
<code>exception werkzeug.exceptions.HTTPUnicodeError</code> </dt> <dd>
<p>This exception is used to signal unicode decode errors of request data. For more information see the <a class="reference internal" href="../unicode/index#unicode"><span class="std std-ref">Unicode</span></a> chapter.</p> </dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.ClientDisconnected">
<code>exception werkzeug.exceptions.ClientDisconnected(description=None, response=None)</code> </dt> <dd>
<p>Internal exception that is raised if Werkzeug detects a disconnected client. Since the client is already gone at that point attempting to send the error message to the client might not work and might ultimately result in another exception in the server. Mainly this is here so that it is silenced by default as far as Werkzeug is concerned.</p> <p>Since disconnections cannot be reliably detected and are unspecified by WSGI to a large extent this might or might not be raised if a client is gone.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.8.</span></p> </div> </details>
</dd>
</dl> <dl class="exception"> <dt id="werkzeug.exceptions.SecurityError">
<code>exception werkzeug.exceptions.SecurityError(description=None, response=None)</code> </dt> <dd>
<p>Raised if something triggers a security error. This is otherwise exactly like a bad request error.</p> <details class="changelog"> <summary>Changelog</summary><div class="versionadded"> <p><span class="versionmodified">New in version 0.9.</span></p> </div> </details>
</dd>
</dl>   <h2 id="baseclass">Baseclass</h2> <p>All the exceptions implement this common interface:</p> <dl class="exception"> <dt id="werkzeug.exceptions.HTTPException">
<code>exception werkzeug.exceptions.HTTPException(description=None, response=None)</code> </dt> <dd>
<p>Baseclass for all HTTP exceptions. This exception can be called as WSGI application to render a default error page or you can catch the subclasses of it independently and render nicer error messages.</p> <dl class="method"> <dt id="werkzeug.exceptions.HTTPException.__call__">
<code>__call__(environ, start_response)</code> </dt> <dd>
<p>Call the exception as WSGI application.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr>
<th class="field-name">Parameters:</th>
<td class="field-body">
<ul class="first last simple"> <li>
<strong>environ</strong> – the WSGI environment.</li> <li>
<strong>start_response</strong> – the response callable provided by the WSGI server.</li> </ul> </td> </tr>  </table> </dd>
</dl> <dl class="method"> <dt id="werkzeug.exceptions.HTTPException.get_response">
<code>get_response(environ=None)</code> </dt> <dd>
<p>Get a response object. If one was passed to the exception it’s returned directly.</p> <table class="docutils field-list" frame="void" rules="none"> <col class="field-name"> <col class="field-body">  <tr>
<th class="field-name">Parameters:</th>
<td class="field-body">
<strong>environ</strong> – the optional environ for the request. This can be used to modify the response depending on how the request looked like.</td> </tr> <tr>
<th class="field-name">Returns:</th>
<td class="field-body">a <code>Response</code> object or a subclass thereof.</td> </tr>  </table> </dd>
</dl> </dd>
</dl>   <h2 id="special-http-exceptions">Special HTTP Exceptions</h2> <p>Starting with Werkzeug 0.3 some of the builtin classes raise exceptions that look like regular python exceptions (eg <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#KeyError" title="(in Python v3.8)"><code>KeyError</code></a>) but are <a class="reference internal" href="#werkzeug.exceptions.BadRequest" title="werkzeug.exceptions.BadRequest"><code>BadRequest</code></a> HTTP exceptions at the same time. This decision was made to simplify a common pattern where you want to abort if the client tampered with the submitted form data in a way that the application can’t recover properly and should abort with <code>400 BAD REQUEST</code>.</p> <p>Assuming the application catches all HTTP exceptions and reacts to them properly a view function could do the following safely and doesn’t have to check if the keys exist:</p> <pre data-language="python">def new_post(request):
    post = Post(title=request.form['title'], body=request.form['body'])
    post.save()
    return redirect(post.url)
</pre> <p>If <code>title</code> or <code>body</code> are missing in the form, a special key error will be raised which behaves like a <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#KeyError" title="(in Python v3.8)"><code>KeyError</code></a> but also a <a class="reference internal" href="#werkzeug.exceptions.BadRequest" title="werkzeug.exceptions.BadRequest"><code>BadRequest</code></a> exception.</p> <dl class="exception"> <dt id="werkzeug.exceptions.BadRequestKeyError">
<code>exception werkzeug.exceptions.BadRequestKeyError(arg=None, *args, **kwargs)</code> </dt> <dd>
<p>An exception that is used to signal both a <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#KeyError" title="(in Python v3.8)"><code>KeyError</code></a> and a <a class="reference internal" href="#werkzeug.exceptions.BadRequest" title="werkzeug.exceptions.BadRequest"><code>BadRequest</code></a>. Used by many of the datastructures.</p> </dd>
</dl>   <h2 id="simple-aborting">Simple Aborting</h2> <p>Sometimes it’s convenient to just raise an exception by the error code, without importing the exception and looking up the name etc. For this purpose there is the <a class="reference internal" href="#werkzeug.exceptions.abort" title="werkzeug.exceptions.abort"><code>abort()</code></a> function.</p> <dl class="function"> <dt id="werkzeug.exceptions.abort">
<code>werkzeug.exceptions.abort(status, *args, **kwargs)</code> </dt> <dd>
<p>Raises an <a class="reference internal" href="#werkzeug.exceptions.HTTPException" title="werkzeug.exceptions.HTTPException"><code>HTTPException</code></a> for the given status code or WSGI application.</p> <p>If a status code is given, it will be looked up in the list of exceptions and will raise that exception. If passed a WSGI application, it will wrap it in a proxy WSGI exception and raise that:</p> <pre data-language="python">abort(404)  # 404 Not Found
abort(Response('Hello World'))
</pre> </dd>
</dl> <p>If you want to use this functionality with custom exceptions you can create an instance of the aborter class:</p> <dl class="class"> <dt id="werkzeug.exceptions.Aborter">
<code>class werkzeug.exceptions.Aborter(mapping=None, extra=None)</code> </dt> <dd>
<p>When passed a dict of code -&gt; exception items it can be used as callable that raises exceptions. If the first argument to the callable is an integer it will be looked up in the mapping, if it’s a WSGI application it will be raised in a proxy exception.</p> <p>The rest of the arguments are forwarded to the exception constructor.</p> </dd>
</dl>   <h2 id="custom-errors">Custom Errors</h2> <p>As you can see from the list above not all status codes are available as errors. Especially redirects and other non 200 status codes that do not represent errors are missing. For redirects you can use the <code>redirect()</code> function from the utilities.</p> <p>If you want to add an error yourself you can subclass <a class="reference internal" href="#werkzeug.exceptions.HTTPException" title="werkzeug.exceptions.HTTPException"><code>HTTPException</code></a>:</p> <pre data-language="python">from werkzeug.exceptions import HTTPException

class PaymentRequired(HTTPException):
    code = 402
    description = '&lt;p&gt;Payment required.&lt;/p&gt;'
</pre> <p>This is the minimal code you need for your own exception. If you want to add more logic to the errors you can override the <code>get_description()</code>, <code>get_body()</code>, <code>get_headers()</code> and <a class="reference internal" href="#werkzeug.exceptions.HTTPException.get_response" title="werkzeug.exceptions.HTTPException.get_response"><code>get_response()</code></a> methods. In any case you should have a look at the sourcecode of the exceptions module.</p> <p>You can override the default description in the constructor with the <code>description</code> parameter:</p> <pre data-language="python">raise BadRequest(description='Request failed because X was not present')
</pre>
<div class="_attribution">
  <p class="_attribution-p">
    © 2007–2020 Pallets<br>Licensed under the BSD 3-clause License.<br>
    <a href="https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/" class="_attribution-link">https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
